#!/bin/bash
echo "Start Application"

cd $OPENSHIFT_HOMEDIR/jetty-8.1/jetty-8.1.11/

CMD="java -jar start.jar -Djetty.host=$OPENSHIFT_JETTY_IP -Djetty.port=$OPENSHIFT_JETTY_PORT"

nohup $CMD > $OPENSHIFT_JETTY_LOG_DIR/server.log 2>&1 &

echo $! > $OPENSHIFT_HOMEDIR/jetty-8.1/run/jetty.pid
