#!/bin/bash
#
echo "Stop Application"

cd $OPENSHIFT_HOMEDIR/jetty-8.1/run

    # Ensure the process is actually running.
    if ps -p `cat jetty.pid` > /dev/null
    then
kill `cat jetty.pid`
    fi

exit 0
